"""empty message

Revision ID: 49857d4f29cb
Revises: c3473882e732
Create Date: 2019-03-29 22:46:52.814005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49857d4f29cb'
down_revision = 'c3473882e732'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demo')
    # ### end Alembic commands ###
